In [42]:
# to write the code and then not change the evrey the output 
# the manual_seed (zero that'S why) the out not change 
import torch
import torch.nn as nn

input=torch.tensor([1.0,2.0,3.0])
neuron=nn.Linear(in_features=3 , out_features=1)
output=neuron(input)

In [43]:
torch.manual_seed(42)
output


tensor([1.5244], grad_fn=<ViewBackward0>)

In [44]:
neuron.weight

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)

In [45]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)