# this code represents the first step in building a neural network using PyTorch. It creates a simple neuron, takes input data, and produces an output based on weights and bias.
# In neural networks, the output is different every time because the weights and bias values are initialized randomly.

In [35]:
import torch
import torch.nn as nn   # Used to build neural networks

# Create input tensor (multi-dimensional array)
x = torch.tensor([1.0, 2.0, 3.0])

# Create a single neuron (3 inputs → 1 output)
neuron = nn.Linear(in_features=3, out_features=1)

# Pass input through the neuron
output = neuron(x)

print(output)

tensor([-0.4016], grad_fn=<ViewBackward0>)

In [36]:
neuron.weight

Parameter containing:
tensor([[-0.1382,  0.4817, -0.4140]], requires_grad=True)

In [37]:
neuron.bias

Parameter containing:
tensor([0.0150], requires_grad=True)

In [38]:
 # to verify the formula 
neuron.weight @ input +neuron.bias

tensor([-0.4016], grad_fn=<AddBackward0>)

In [ ]:
# tensor([-0.4016], grad_fn=<ViewBackward0>) == tensor([-0.4016], grad_fn=<AddBackward0>) 
# the  both output  verified output are same gives the aanswer